apiVersion: v1
kind: Pod
metadata:
  name: bizaar
spec:
  containers:
    - name: bizaar
      image: zulhcivo/bizaar:v1alpha1
      imagePullPolicy: Always
      args: ["sleep", "86400"]
  imagePullSecrets:
    - name: regcred
