apiVersion: v1
kind: Pod
metadata:
  name: kubemart
spec:
  containers:
    - name: kubemart
      image: civo/kubemart-daemon:v1alpha1
      imagePullPolicy: Always
      args: ["sleep", "86400"]
  # imagePullSecrets:
  #   - name: regcred
